services:
  service-desk-api:
    container_name: service-desk-api-container
    build:
      context: .
      dockerfile: ./ServiceDeskApi/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - service-desk-db
    networks:
      - app_network
  
  service-desk-db:
    image: postgres:17
    container_name: service-desk-db-container
    restart: always
    networks:
      - app_network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 3dxlq0tj
      POSTGRES_DB: service-desk-db
    ports:
      - "5432:5432"
    volumes:
      - service-desk-db_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  service-desk-db_data:
    
    